### ISSUE TITLE
error

### ISSUE THREAD

**Issue by loicbramoulle** [hannesdelbeke/mesh-data-transfer#1]
Hi, I just bought a again the addon on gumroad for support.
Whatever I do I get this error. TRied blender 3.5, 3.6, 4.1, addon version 2.02 2.03, vertex ID, UV (both meshes have exact same UVs.)
Trying to transfer the shape (realistic CC4 to cartoony CC4 character.)

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MeshDataTransfer\operators.py", line 115, in execute
    transfer_data = MeshDataTransfer(target=active, source =source, world_space=world_space,
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MeshDataTransfer\mesh_data_transfer.py", line 633, in __init__
    self.cast_verts()
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MeshDataTransfer\mesh_data_transfer.py", line 1141, in cast_verts
    self.related_ids = np.zeros(v_count * 3, dtype=np.int)
  File "C:\Users\Admin\AppData\Roaming\Python\Python310\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'? 
```

**Comment by loicbramoulle** [comment]
Tried with basic cube and same error.

**Comment by loicbramoulle** [comment]
Tried 1.44 too, so strange, I remember that it worked !..

**Comment by loicbramoulle** [comment]
trying to transfer vertex groups also gives the same error.

**Comment by jn-jairo** [comment]
@loicbramoulle I just tried the version 2.0.5 from gumroad and it is working.

I believe this github mirror is not updated with that new version.

**Comment by loicbramoulle** [comment]
Hum I just tried 2.0.5 and still exact same error: "did you mean 'inf' ?"
blender 3.6 and 4.1
I'm trying to transfer the shape using the same exact UVs, but any other transfer does the same error too.
It's all functions, all version of addon, and all version of blender, so no idea how that's possible if it's only on my end, I don't see how my prefs could create this issue.

**Comment by hannesdelbeke** [comment]
i checked the code and it seems to be updated fron `np.int` to `np.int64`
so it shouldnt be possible to get the same error if you are using the new addon.
- can you post the full error again

in the error it will post the location of the file. ensure this has been updated, e.g. :
```
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MeshDataTransfer\mesh_data_transfer.py", line 1141, in cast_verts
    self.related_ids = np.zeros(v_count * 3, dtype=np.int)
```

**Comment by loicbramoulle** [comment]
Hi thanks, after a restart the error doesn't appear in 4.1.
But I remembered it was able to transfer shapes using two mesh with the same exact topology & UVs (different character designs with different vertex groups, but same topology/UVs, Character Creator ect..)
And I just tried on a subdivided cube, it doesn't seem to be able to transfer a modification of the shape using the UVs:
![image](https://github.com/hannesdelbeke/mesh-data-transfer/assets/49880198/38bfb319-e8fe-4728-932f-2b82feaa008b)
![image](https://github.com/hannesdelbeke/mesh-data-transfer/assets/49880198/dc481852-90ad-4378-bd5e-0e002acd36d3)
Thanks anyway !
Maybe I can rather transfer the vertex groups.

**Comment by hannesdelbeke** [comment]
maybe this video can help you https://www.youtube.com/watch?v=CvMeK_IIw-Y

**Comment by loicbramoulle** [comment]
Thanks, actually vertex ID works, not sure why it fails with UVs on a simple default cube usecase, but not sure I ever managed to get it to use UVs, maybe all the times I managed to transfer it was using vertex ID.
Thanks !
